[status]
separator_open  = "░▒▓"
separator_close = "▓▒░"
separator_style = { fg = "black", bg = "black" }

mode_normal = { bg = "blue"   , fg = "black", bold = true }
mode_select = { bg = "magenta", fg = "black", bold = true }
mode_unset  = { bg = "white"  , fg = "black", bold = true }

progress_label  = { fg = "black", bold = true }
progress_normal = { fg = "blue" , bg = "black" }
progress_error  = { fg = "red"  , bg = "black" }

[manager]
preview_hovered = { reversed = true }

[filetype]
rules = [
  { mime = "image/*", fg = "magenta"      },
  { mime = "video/*", fg = "lightmagenta" },

  { name = "*.{alac,ape,flac,wav}", fg = "cyan", bold = true },

  { mime = "audio/*", fg = "cyan" },

  { name = "*.{bak,crdownload,dpkg-dist,dpkg-new,dpkg-old,dpkg-tmp,old,orig,part,rej,rpmnew,rpmorig,rpmsave,swp,tmp,ucf-dist,ucf-new,ucf-old,swn,swo,bk,~}", fg = "lightblack" },

  { name = "*.{asc,enc,gpg,p12,pfx,pgp,sig,signature}", fg = "lightcyan" }, 

  { name = "*.{djvu,doc,dvi,eml,eps,key,odp,odt,pdf,ppt,rtf,xls,pptx,docx,fotd,xlsx}", fg = "blue" },

  { name = "*.{tar,tgz,arc,arj,taz,lha,lz4,lzh,lzma,tlz,txz,tzo,t7z,zip,z,dz,gz,lrz,lz,lzo,xz,zst,tzst,bz2,bz,tbz,tbz2,tz,deb,rpm,jar,war,ear,sar,rar,alz,ace,zoo,cpio,7z,rz,cab,wim,swm,dwm,esd}", fg = "lightred", bold = true },
  
  { name = "*Makefile"         , fg = "yellow" },
  { name = "*Cargo.toml"       , fg = "yellow" }, 
  { name = "*SConstruct"       , fg = "yellow" }, 
  { name = "*CMakeLists.txt"   , fg = "yellow" },
  { name = "*build.gradle"     , fg = "yellow" }, 
  { name = "*pom.xml"          , fg = "yellow" }, 
  { name = "*Rakefile"         , fg = "yellow" }, 
  { name = "*package.json"     , fg = "yellow" }, 
  { name = "*Gruntfile.js"     , fg = "yellow" },
  { name = "*Gruntfile.coffee" , fg = "yellow" }, 
  { name = "*BUILD"            , fg = "yellow" }, 
  { name = "*BUILD.bazel"      , fg = "yellow" }, 
  { name = "*WORKSPACE"        , fg = "yellow" }, 
  { name = "*build.xml"        , fg = "yellow" }, 
  { name = "*Podfile"          , fg = "yellow" },
  { name = "*webpack.config.js", fg = "yellow" }, 
  { name = "*meson.build"      , fg = "yellow" }, 
  { name = "*composer.json"    , fg = "yellow" }, 
  { name = "*RoboFile.php"     , fg = "yellow" }, 
  { name = "*PKGBUILD"         , fg = "yellow" },
  { name = "*Justfile"         , fg = "yellow" }, 
  { name = "*Procfile"         , fg = "yellow" }, 
  { name = "*Dockerfile"       , fg = "yellow" }, 
  { name = "*Containerfile"    , fg = "yellow" }, 
  { name = "*Vagrantfile"      , fg = "yellow" }, 
  { name = "*Brewfile"         , fg = "yellow" },
  { name = "*Gemfile"          , fg = "yellow" }, 
  { name = "*Pipfile"          , fg = "yellow" }, 
  { name = "*build.sbt"        , fg = "yellow" }, 
  { name = "*mix.exs"          , fg = "yellow" }, 
  { name = "*bsconfig.json"    , fg = "yellow" }, 
  { name = "*tsconfig.json"    , fg = "yellow" },
  
  { name = "*.{class,o,hi,ko,pyc,elc,zwc,jar}", fg = "lightyellow" },

  { name = "*.{cmd,sh,exe,com,btm,bat,ps1,fish}", fg = "green" },

  { mime = "inode/x-empty", fg = "black" },

  { name = "*" , is = "block" , fg = "yellow"     , bold = true },
  { name = "*" , is = "char"  , fg = "yellow"     , bold = true },
  { name = "*" , is = "fifo"  , fg = "lightyellow", bold = true },
  { name = "*" , is = "link"  , fg = "cyan"       , bold = true },
  { name = "*/", is = "link"  , fg = "lightcyan"  , bold = true },
  { name = "*" , is = "orphan", fg = "red"        , bold = true },
  { name = "*" , is = "sock"  , fg = "magenta"    , bold = true },
  { name = "*" , is = "sticky", fg = "lightblue"                },
  { name = "*/", is = "sticky", fg = "lightblue"  , bold = true },
  { name = "*" , is = "exec"  , fg = "green"      , bold = true },
  { name = "*" ,                fg = "white"                    }, 
  { name = "*/",                fg = "blue"       , bold = true }
]

[icon]
dirs = [
  { name = "bin"  , text = "", fg = "green" },
  { name = "boot" , text = "󰤆", fg = "lightblue" },
  { name = "dev"  , text = "󰾰", fg = "white" },
  { name = "etc"  , text = "󰯠", fg = "cyan" },
  { name = "home" , text = "", fg = "magenta" },
  { name = "lib"  , text = "", fg = "yellow" },
  { name = "lib64", text = "", fg = "lightyellow" },
  { name = "mnt"  , text = "", fg = "white" },
  { name = "nix"  , text = "󱄅", fg = "blue" },
  { name = "opt"  , text = "󰩦", fg = "black" },
  { name = "proc" , text = "", fg = "lightred" },
  { name = "root" , text = "󱇐", fg = "red" },
  { name = "run"  , text = "", fg = "lightgreen" },
  { name = "srv"  , text = "", fg = "white" },
  { name = "sys"  , text = "", fg = "lightred" },
  { name = "tmp"  , text = "󰅒", fg = "lightblack" },
  { name = "usr"  , text = "", fg = "lightmagenta" },
  { name = "var"  , text = "", fg = "lightcyan" },

  { name = "hdd"         , text = "󰋊", fg = "white" },
  { name = "store"       , text = "", fg = "magenta" },
  { name = "win"         , text = "󰝘", fg = "blue" },
  { name = "icons"       , text = "󰇲", fg = "magenta" },
  { name = "assets"      , text = "", fg = "magenta" },
  { name = "database"    , text = "", fg = "white" },
  { name = "preset"      , text = "󰲃", fg = "white" },
  { name = "scripts"     , text = "󰯃", fg = "green" },
  { name = "target"      , text = "󰓾", fg = "yellow" },
  { name = "nixos"       , text = "󱄅", fg = "blue" },
  { name = "home-manager", text = "󱄫", fg = "blue" },
  { name = "src"         , text = "󰅪", fg = "lightgreen" },
  { name = "include"     , text = "⊆", fg = "lightgreen" },
  { name = "lavalink"    , text = "󱪄", fg = "red" },
  { name = "error"       , text = "", fg = "red" },
  { name = "component"   , text = "󰆧", fg = "yellow" },
  { name = "model"       , text = "󰆩", fg = "lightyellow" },
  { name = "command"     , text = "", fg = "lightgreen" },
  { name = "core"        , text = "󰹻", fg = "green" },
  { name = "test"        , text = "󰤑", fg = "cyan" },
  
  { name = "plugin"      , text = "", fg = "magenta" },
  { name = "plugins"     , text = "", fg = "magenta" },
  { name = "ext"         , text = "", fg = "magenta" },

  { name = "Applications", text = "󰏖", fg = "green" },
  { name = "Documents"   , text = "󱔘", fg = "blue" },
  { name = "Downloads"   , text = "󱃩", fg = "white" },
  { name = "Music"       , text = "󰼄", fg = "cyan" },
  { name = "Pictures"    , text = "󰋯", fg = "magenta" },
  { name = "Videos"      , text = "󰪐", fg = "lightmagenta" },
  { name = "Games"       , text = "󰺷", fg = "red" },
  { name = "Code"        , text = "", fg = "yellow" },

  { name = "Screenshots" , text = "󰹑", fg = "white" },
  { name = "Wallpapers"  , text = "󰸉", fg = "white" },

  { name = ".cache"              , text = "", fg = "lightblack" },
  { name = ".config"             , text = "", fg = "lightblack" },
  { name = ".icons"              , text = "󰇲", fg = "lightblack" },
  { name = ".local"              , text = "󰌢", fg = "lightblack" },
  { name = ".pki"                , text = "󱆈", fg = "lightblack" },
  { name = ".ssh"                , text = "󰷖", fg = "lightblack" },
  { name = ".mozilla"            , text = "", fg = "lightblack" },
  { name = ".steam"              , text = "", fg = "lightblack" },
  { name = ".SteamCloud"         , text = "", fg = "lightblack" },
  { name = ".vscode"             , text = "󰨞", fg = "lightblack" },
  { name = ".muse-sounds-manager", text = "󰙽", fg = "lightblack" },

  { name = ".cargo" , text = "󱣘", fg = "yellow" },
  { name = ".devenv", text = "󱇚", fg = "blue" },
  { name = ".git"   , text = "", fg = "lightblack" },
  { name = ".github", text = "", fg = "magenta" },

  { name = ".dup"  , text = "", fg = "lightyellow" },
  { name = ".hid"  , text = "", fg = "yellow" },
  { name = ".priv" , text = "", fg = "lightred" },
  { name = ".nsfw" , text = "", fg = "red" },
  { name = ".old"  , text = "󱈎", fg = "lightblack" },
  { name = ".trash", text = "", fg = "black" },
]

prepend_files = [
  { name = ".manpath"	      , text = "", fg_dark = "red" },
  { name = ".steampath"	      , text = "", fg_dark = "blue" },
  { name = ".steampid"	      , text = "", fg_dark = "blue" },
  { name = ".envrc"           , text = "󰌪", fg_dark = "green" },
  { name = ".codespellrc"     , text = "󰓆", fg_dark = "blue" },
  { name = "Cargo.toml"       , text = "󱢜", fg_dark = "yellow" },
  { name = "Cargo.lock"       , text = "󱢜", fg_dark = "yellow" },
  { name = ".devenv.flake.nix", text = "󰾍", fg_dark = "cyan" },
  { name = "devenv.nix"       , text = "󰾍", fg_dark = "cyan" },
  { name = "devenv.yaml"      , text = "󰾍", fg_dark = "cyan" },
  { name = "devenv.lock"      , text = "󰾍", fg_dark = "cyan" },
  { name = "flake.lock"       , text = "", fg_dark = "blue" },
  { name = "LICENSE"          , text = "", fg_dark = "#cbcb41", fg_light = "#666620" },
]

conds = [
  { cond = "block"       , text = "", fg = "yellow"     , bold = true },
  { cond = "char"        , text = "󱊞", fg = "yellow"     , bold = true },
  { cond = "fifo"        , text = "󰟥", fg = "lightyellow", bold = true },
  { cond = "link & dir"  , text = "", fg = "lightcyan"  , bold = true },
  { cond = "link"        , text = "󰌹", fg = "cyan"       , bold = true },
  { cond = "orphan"      , text = "󰌺", fg = "red"        , bold = true },
  { cond = "sock"        , text = "󰐧", fg = "magenta"    , bold = true },
  { cond = "sticky & dir", text = "", fg = "lightblue"  , bold = true },
  { cond = "sticky"      , text = "󱍤", fg = "lightblue"                },
  { cond = "dir"         , text = "", fg = "blue"       , bold = true },
  { cond = "exec"        , text = "", fg = "green"      , bold = true }, 
  { cond = "!dir"        , text = "󰈔", fg = "white"                    }	
]
