[status]
separator_open  = "░▒▓"
separator_close = "▓▒░"
separator_style = { fg = "black", bg = "black" }

mode_normal = { bg = "blue"   , fg = "black", bold = true }
mode_select = { bg = "magenta", fg = "black", bold = true }
mode_unset  = { bg = "white"  , fg = "black", bold = true }

progress_label  = { fg = "black", bold = true }
progress_normal = { fg = "blue" , bg = "black" }
progress_error  = { fg = "red"  , bg = "black" }

[mgr]
preview_hovered = { reversed = true }

count_copied   = { fg = "black", bg = "green" }
count_cut      = { fg = "black", bg = "red" }
count_selected = { fg = "black", bg = "yellow" }

[filetype]
rules = [
  { mime = "image/*", fg = "magenta"      },
  { mime = "video/*", fg = "lightmagenta" },

  { name = "*.{alac,ape,flac,wav}", fg = "cyan", bold = true },

  { mime = "audio/*", fg = "cyan" },

  { name = "*.{bak,crdownload,dpkg-dist,dpkg-new,dpkg-old,dpkg-tmp,old,orig,part,rej,rpmnew,rpmorig,rpmsave,swp,tmp,ucf-dist,ucf-new,ucf-old,swn,swo,bk,~}", fg = "lightblack" },

  { name = "*.{asc,enc,gpg,p12,pfx,pgp,sig,signature}", fg = "lightcyan" },

  { name = "*.{djvu,doc,dvi,eml,eps,key,odp,odt,pdf,ppt,rtf,xls,pptx,docx,fotd,xlsx}", fg = "blue" },

  { name = "*.{tar,tgz,arc,arj,taz,lha,lz4,lzh,lzma,tlz,txz,tzo,t7z,zip,z,dz,gz,lrz,lz,lzo,xz,zst,tzst,bz2,bz,tbz,tbz2,tz,deb,rpm,jar,war,ear,sar,rar,alz,ace,zoo,cpio,7z,rz,cab,wim,swm,dwm,esd}", fg = "lightred", bold = true },

  { name = "*Makefile"         , fg = "yellow" },
  { name = "*Cargo.toml"       , fg = "yellow" },
  { name = "*SConstruct"       , fg = "yellow" },
  { name = "*CMakeLists.txt"   , fg = "yellow" },
  { name = "*build.gradle"     , fg = "yellow" },
  { name = "*pom.xml"          , fg = "yellow" },
  { name = "*Rakefile"         , fg = "yellow" },
  { name = "*package.json"     , fg = "yellow" },
  { name = "*Gruntfile.js"     , fg = "yellow" },
  { name = "*Gruntfile.coffee" , fg = "yellow" },
  { name = "*BUILD"            , fg = "yellow" },
  { name = "*BUILD.bazel"      , fg = "yellow" },
  { name = "*WORKSPACE"        , fg = "yellow" },
  { name = "*build.xml"        , fg = "yellow" },
  { name = "*Podfile"          , fg = "yellow" },
  { name = "*webpack.config.js", fg = "yellow" },
  { name = "*meson.build"      , fg = "yellow" },
  { name = "*composer.json"    , fg = "yellow" },
  { name = "*RoboFile.php"     , fg = "yellow" },
  { name = "*PKGBUILD"         , fg = "yellow" },
  { name = "*Justfile"         , fg = "yellow" },
  { name = "*Procfile"         , fg = "yellow" },
  { name = "*Dockerfile"       , fg = "yellow" },
  { name = "*Containerfile"    , fg = "yellow" },
  { name = "*Vagrantfile"      , fg = "yellow" },
  { name = "*Brewfile"         , fg = "yellow" },
  { name = "*Gemfile"          , fg = "yellow" },
  { name = "*Pipfile"          , fg = "yellow" },
  { name = "*build.sbt"        , fg = "yellow" },
  { name = "*mix.exs"          , fg = "yellow" },
  { name = "*bsconfig.json"    , fg = "yellow" },
  { name = "*tsconfig.json"    , fg = "yellow" },
  { name = "*README.md"        , fg = "yellow" },
  { name = "*flake.nix"        , fg = "yellow" },

  { name = "*.{class,o,hi,ko,pyc,elc,zwc,jar}", fg = "lightyellow" },

  { name = "*.{cmd,sh,exe,com,btm,bat,ps1,fish}", fg = "green" },

  { mime = "inode/x-empty", fg = "black" },

  { name = "*" , is = "block" , fg = "yellow"     , bold = true },
  { name = "*" , is = "char"  , fg = "yellow"     , bold = true },
  { name = "*" , is = "fifo"  , fg = "lightyellow", bold = true },
  { name = "*" , is = "orphan", fg = "red"        , bold = true },
  { name = "*" , is = "link"  , fg = "cyan"       , bold = true },
  { name = "*/", is = "link"  , fg = "lightcyan"  , bold = true },
  { name = "*" , is = "sock"  , fg = "magenta"    , bold = true },
  { name = "*" , is = "sticky", fg = "lightblue"                },
  { name = "*/", is = "sticky", fg = "lightblue"  , bold = true },
  { name = "*" , is = "exec"  , fg = "green"      , bold = true },
  { name = "*" ,                fg = "white"                    },
  { name = "*/",                fg = "blue"       , bold = true }
]

[icon]
dirs = [
  { name = "bin"  , text = "" },
  { name = "boot" , text = "󰤆" },
  { name = "dev"  , text = "󰾰" },
  { name = "etc"  , text = "󰯠" },
  { name = "home" , text = "" },
  { name = "lib"  , text = "" },
  { name = "lib64", text = "" },
  { name = "mnt"  , text = "" },
  { name = "nix"  , text = "󱄅" },
  { name = "opt"  , text = "󰩦" },
  { name = "proc" , text = "" },
  { name = "root" , text = "󱇐" },
  { name = "run"  , text = "" },
  { name = "srv"  , text = "" },
  { name = "sys"  , text = "" },
  { name = "tmp"  , text = "󰅒" },
  { name = "usr"  , text = "" },
  { name = "var"  , text = "" },

  { name = "hdd"         , text = "󰋊" },
  { name = "store"       , text = "" },
  { name = "win"         , text = "󰝘" },
  { name = "icons"       , text = "󰇲" },
  { name = "assets"      , text = "" },
  { name = "database"    , text = "" },
  { name = "preset"      , text = "󰲃" },
  { name = "scripts"     , text = "󰯃" },
  { name = "target"      , text = "󰓾" },
  { name = "nixos"       , text = "󱄅" },
  { name = "home-manager", text = "󱄫" },
  { name = "src"         , text = "󰅪" },
  { name = "include"     , text = "⊆" },
  { name = "lavalink"    , text = "󱪄" },
  { name = "error"       , text = "" },
  { name = "component"   , text = "󰆧" },
  { name = "model"       , text = "󰆩" },
  { name = "command"     , text = "" },
  { name = "core"        , text = "󰹻" },
  { name = "test"        , text = "󰤑" },

  { name = "plugin"      , text = "" },
  { name = "plugins"     , text = "" },
  { name = "ext"         , text = "" },

  { name = "Applications", text = "󰏖" },
  { name = "Documents"   , text = "󱔘" },
  { name = "Downloads"   , text = "󱃩" },
  { name = "Music"       , text = "󰼄" },
  { name = "Pictures"    , text = "󰋯" },
  { name = "Videos"      , text = "󰪐" },
  { name = "Games"       , text = "󰺷" },
  { name = "Code"        , text = "" },

  { name = "Screenshots" , text = "󰹑" },
  { name = "Wallpapers"  , text = "󰸉" },

  { name = ".cache"              , text = "" },
  { name = ".config"             , text = "" },
  { name = ".icons"              , text = "󰇲" },
  { name = ".local"              , text = "󰌢" },
  { name = ".pki"                , text = "󱆈" },
  { name = ".ssh"                , text = "󰷖" },
  { name = ".mozilla"            , text = "" },
  { name = ".steam"              , text = "" },
  { name = ".SteamCloud"         , text = "" },
  { name = ".vscode"             , text = "󰨞" },
  { name = ".muse-sounds-manager", text = "󰙽" },
  { name = ".java"		 , text = "" },
  { name = ".zen"		 , text = "󰗝" },

  { name = ".cargo" , text = "󱣘" },
  { name = ".devenv", text = "󱇚" },
  { name = ".git"   , text = "" },
  { name = ".github", text = "" },

  { name = ".dup"  , text = "" },
  { name = ".hid"  , text = "" },
  { name = ".priv" , text = "" },
  { name = ".nsfw" , text = "" },
  { name = ".old"  , text = "󱈎" },
  { name = ".trash", text = "" },
]

prepend_files = [
  { name = ".manpath"	      , text = "" },
  { name = ".steampath"	      , text = "" },
  { name = ".steampid"	      , text = "" },
  { name = ".envrc"           , text = "󰌪" },
  { name = ".codespellrc"     , text = "󰓆" },
  { name = "Cargo.toml"       , text = "󱢜" },
  { name = "Cargo.lock"       , text = "󱢜" },
  { name = ".devenv.flake.nix", text = "󰾍" },
  { name = "devenv.nix"       , text = "󰾍" },
  { name = "devenv.yaml"      , text = "󰾍" },
  { name = "devenv.lock"      , text = "󰾍" },
  { name = "flake.lock"       , text = "" },
  { name = "LICENSE"          , text = "" },
]

conds = [
  { if = "block"       , text = "", fg = "yellow"     , bold = true },
  { if = "char"        , text = "󱊞", fg = "yellow"     , bold = true },
  { if = "fifo"        , text = "󰟥", fg = "lightyellow", bold = true },
  { if = "link & dir"  , text = "", fg = "lightcyan"  , bold = true },
  { if = "orphan"      , text = "󰌺", fg = "red"        , bold = true },
  { if = "link"        , text = "󰌹", fg = "cyan"       , bold = true },
  { if = "sock"        , text = "󰐧", fg = "magenta"    , bold = true },
  { if = "sticky & dir", text = "", fg = "lightblue"  , bold = true },
  { if = "sticky"      , text = "󱍤", fg = "lightblue"                },
  { if = "dir"         , text = "", fg = "blue"       , bold = true },
  { if = "exec"        , text = "", fg = "green"      , bold = true },
  { if = "!dir"        , text = "󰈔", fg = "white"                    }
]
